kind: pipeline
type: docker
name: default

steps:
  - name: r_test
    image: r-base:latest
    commands:
      - pwd
      #- Rscript ./test.r
      #- Rscript -e "install.packages('testthat', repo='https://packagemanager.rstudio.com/cran/2022-08-01')"
      #- Rscript ./test_cases.r
      - Rscrpt -e "print(passte0('Available packages: ', .packages(all.available = TRUE)))"
      - Rscript -e "install.packages('lintr', repo='https://packagemanager.rstudio.com/cran/2022-08-24')"
      - Rscript -e "library(lintr); lint('test_linter.r')"
