kind: pipeline
type: docker
name: default

steps:
  - name: r_test
    image: r-base:latest
    commands:
      - pwd
      #- Rscript ./test.r
      #- Rscript -e "install.packages('testthat', repo='https://packagemanager.rstudio.com/cran/2022-08-01')"
      #- Rscript ./test_cases.r
      - apt-get update
      - apt-get -y install libxml2-dev    # avoid prompt: default to yes
      - Rscript -e "install.packages(c('R6', 'processx', 'callr', 'desc', 'stringi'), repo='https://packagemanager.rstudio.com/cran/2022-08-24', lib = '/usr/local/lib/R/site-library')"
      - Rscript -e "install.packages('lintr', repo='https://packagemanager.rstudio.com/cran/2022-08-24', lib = '/usr/local/lib/R/site-library')"
      - Rscript -e "library(lintr); lint('test_linter.r')"

trigger:
  event:
    - push
    #- pull_request
  branch:
    - master
